import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "var(--color-text)",
        paper: "var(--color-bg)",
        moss: "var(--color-accent)",
        surface: "var(--color-surface)",
        "surface-muted": "var(--color-surface-muted)",
        primary: "var(--color-text)",
        muted: "var(--color-text-muted)",
        line: "var(--color-border)",
        accent: "var(--color-accent)",
        "accent-soft": "var(--color-accent-soft)",
        danger: "var(--color-danger)",
        "danger-soft": "var(--color-danger-soft)",
        "danger-text": "var(--color-danger-text)",
        warning: "var(--color-warning)",
        "warning-soft": "var(--color-warning-soft)",
        "warning-text": "var(--color-warning-text)",
        success: "var(--color-success)",
        "success-soft": "var(--color-success-soft)",
        "success-text": "var(--color-success-text)",
        info: "var(--color-info)",
        "info-soft": "var(--color-info-soft)",
        "info-text": "var(--color-info-text)",
        "sync-idle": "var(--color-sync-idle)",
        "sync-idle-soft": "var(--color-sync-idle-soft)",
        "sync-idle-text": "var(--color-sync-idle-text)",
        "sync-active": "var(--color-sync-active)",
        "sync-active-soft": "var(--color-sync-active-soft)",
        "sync-active-text": "var(--color-sync-active-text)",
        energy: "var(--color-energy)",
        "energy-soft": "var(--color-energy-soft)",
        "energy-text": "var(--color-energy-text)",
        "energy-muted": "var(--color-energy-muted)",
        care: "var(--color-care)",
        "care-soft": "var(--color-care-soft)",
        "care-text": "var(--color-care-text)",
        proposal: "var(--color-proposal)",
        "proposal-soft": "var(--color-proposal-soft)",
        "proposal-text": "var(--color-proposal-text)",
        "row-warning-soft": "var(--color-row-warning-soft)",
        "row-danger-soft": "var(--color-row-danger-soft)",
        "task-parent": "var(--color-task-parent)",
        "task-child": "var(--color-task-child)",
        "task-row-hover": "var(--color-task-row-hover)",
        "action-muted": "var(--color-action-muted)",
        "action-muted-hover": "var(--color-action-muted-hover)",
        delete: "var(--color-delete)",
        "delete-soft": "var(--color-delete-soft)",
        "delete-hover": "var(--color-delete-hover)",
        "priority-low": "var(--color-priority-low)",
        "priority-medium": "var(--color-priority-medium)",
        "priority-high": "var(--color-priority-high)",
        "status-todo": "var(--color-status-todo)",
        "status-todo-soft": "var(--color-status-todo-soft)",
        "status-todo-text": "var(--color-status-todo-text)",
        "status-next": "var(--color-status-next)",
        "status-next-soft": "var(--color-status-next-soft)",
        "status-next-text": "var(--color-status-next-text)",
        "status-doing": "var(--color-status-doing)",
        "status-doing-soft": "var(--color-status-doing-soft)",
        "status-doing-text": "var(--color-status-doing-text)",
        "status-waiting": "var(--color-status-waiting)",
        "status-waiting-soft": "var(--color-status-waiting-soft)",
        "status-waiting-text": "var(--color-status-waiting-text)",
        "status-blocked": "var(--color-status-blocked)",
        "status-blocked-soft": "var(--color-status-blocked-soft)",
        "status-blocked-text": "var(--color-status-blocked-text)",
        "status-paused": "var(--color-status-paused)",
        "status-paused-soft": "var(--color-status-paused-soft)",
        "status-paused-text": "var(--color-status-paused-text)",
        "status-done": "var(--color-status-done)",
        "status-done-soft": "var(--color-status-done-soft)",
        "status-done-text": "var(--color-status-done-text)",
        "due-near": "var(--color-due-near)",
        "due-near-soft": "var(--color-due-near-soft)",
        "due-over": "var(--color-due-over)",
        "due-over-soft": "var(--color-due-over-soft)",
        coral: "#c75f4b",
        amber: "#b7791f"
      }
    }
  },
  plugins: []
};

export default config;
